### PR TITLE
OLMIS-153 Fix wrong date when updating inventory status through list page

### PR DESCRIPTION
**Pull request by chunky56**
When updating status and setting the decommissioned date, the date actually saved is incorrect. This is probably because the month and day are incorrectly transposed. Also convert from string and add a timezone offset to avoid being off by a day.

### CODE REVIEW

**Comment by eliasmu** [comment]
The timezone issue you were trying to solve here looks to me as something
that could happen across the board in the application. When I first
investigated a similar issue, something like this was happening because
Postgres time zone (something set in the Postgres configuration) was
different from the system time zone (which is picked by the Java runtime).
If my analysis is correct, it might be better to ensure your test
environment has consistent timezone setting for both Postgres and system to
avoid coding a workaround on case by case basis.

**Comment by chunky56** [comment]
Hey Elias,
It may be possible to apply this issue across the board--however, I don't think this issue is a result of a mismatch between the Postgres time zone and the system time zone. My environment uses the same time zone for both and this issue still comes up. I believe the issue is more based on the fact that the date field in the UI does not know about times and time zones, and neither does the SQL field in the equipment_inventories table.
From what I see, when the user enters a date (2016-02-24), it is a string which is then converted to milliseconds from epoch, corresponding to 12AM. The Java code then offsets it based on the current timezone I believe, turning it into something like 2016-02-23 4PM (for PST), and then it is saved into the table with the time truncated, since the field is simply of Date type.
So a user enters 2016-02-24 and it gets saved as 2016-02-23, unless I add this offset in the JS code.
Thoughts from anyone on how to apply this systemwide?

**Comment by eliasmu** [comment]
Hmm, could adding the @JsonDeserialize annotation on the specific field
involved help here? It looks like it is missing [here](
https://github.com/OpenLMIS/open-lmis/blob/dev/modules/equipment/src/main/java/org/openlmis/equipment/domain/EquipmentInventory.java#L51
).

Something like ...
`@JsonDeserialize(using = DateDeserializer.class)
 @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")`

**Comment by chunky56** [comment]
I have used Elias' annotations to deserialize the date string on the JavaScript side to a Date on the Java side and it appears to be working. In discussion with Josh, I have also removed using JavaScript date functions to set and pass a date to the Java side, but rather just pass a date string and let Java handle timezones. Please take a look and give any feedback. Tested most CRUD scenarios.

**Comment by richmag** [comment]
Tested scenario on OLMIS-153, works as expected.  Tested date fields for CC and non-CC equipment via detail page, works good.

**Comment by chunky56** [comment]
Merging, as it builds and tests properly, and no further feedback for a couple of days.

**Pull request merged**
