### PR TITLE
Additional feature toggle changes

### PR DESCRIPTION
**Pull request by chunky56**

### CODE REVIEW

**Comment by benleibert** [comment]
I’m getting build errors related to missing data. Will you please specify the names/order of gradle tasks that should be run?

**Comment by benleibert** [comment]
It would be nice if build.gradle had a comment describing how to use its “enableCustom” flag. It might also be worth putting a description of the feature and its usage in the main README.md file.

**Comment by chunky56** [comment]
It should work with the same set of gradle tasks we've been using for the build: gradle clean setupdb seed build testseed run. What kinds of data errors are you getting?

**Comment by chunky56** [comment]
I'm hesitant to document the enableCustom task too much, as it should not need to be called explicitly. Calling the seed task will run enableCustom automatically, as long as the toggleOnCustom is set to true. Similar to how migrateDB works.

**Comment by benleibert** [comment]
Thank you! I had been trying to explicitly use some of the new tasks, like baseSeed and testSeed, and guess I can do without them. 

In terms of the "enableCustom" task, it might be nice to describe how to use it implicitly. In other words, it would be nice to have a note in the gradle and/or readme files about setting -PtoggleOnCustom to true or false.

**Comment by benleibert** [comment]
Granting/revoking the “Help Content – View” right appropriately toggles the availability of the “Help” link. However, clicking the “Help” link after granting myself permission to it (and re-logging into the system) results in a “You are not authorized to view the requested page” error. Is addressing this beyond the scope of this set of work?

**Comment by chunky56** [comment]
Do you get this "not authorized" error in the dev branch?

**Comment by benleibert** [comment]
I saw it within the /feature/feature-toggle-2 branch, but will try it in the dev branch momentarily.

**Comment by benleibert** [comment]
On an unrelated note, regarding the equipment-related changes in this branch:  when I log in as Admin123, the menu shows the following under Administration -> Equipments:

Equipment Types
Equipment List
Equipment Products

The tabs, however, are displayed in a slightly different order and with different text. From left to right, they are: “Equipment Types,” “Program Equipments & Products,” and “Equipment List.”

As an aside, it would be nice if we can consistently use “Equipment” rather than “Equipments” (with an “s” at the end).

**Comment by benleibert** [comment]
The "Help" link works properly in the dev branch: it takes me to the intended page without error. (The intended page has absolutely no helpful information on it, but that's a separate issue...)

**Comment by chunky56** [comment]
Hmm that's strange, as I'm getting an access denied when accessing the help link when I've built on the dev branch.

**Comment by benleibert** [comment]
Maybe there's some caching at play? Before clearing my cache, I didn't get the "Help" link at all when trying it in "dev."

**Comment by benleibert** [comment]
Which user are you logging in as?

**Comment by chunky56** [comment]
I just use devadmin.

**Comment by chunky56** [comment]
Although I get the same issues with Admin123 and superuser.

**Comment by chunky56** [comment]
I am seeing the same behavior in the dev branch. Are you still seeing access denied in this branch but not dev?

**Comment by benleibert** [comment]
I now see it in the dev branch (and assume I would as well in the "feature-toggle-2" branch).

**Comment by chunky56** [comment]
So I think this branch did not introduce this issue, and the issue is out of scope of this work. If there are no other issues, let's merge this branch.

**Comment by benleibert** [comment]
Okay, that seems reasonable. I'm looking for bugs to address, and can write one for this remaining issue and potentially look at it.

**Comment by benleibert** [comment]
I just remembered this comment, though. Do you think it should be addressed?

regarding the equipment-related changes in this branch: when I log in as Admin123, the menu shows the following under Administration -> Equipments:

Equipment Types
Equipment List
Equipment Products

The tabs, however, are displayed in a slightly different order and with different text. From left to right, they are: “Equipment Types,” “Program Equipments & Products,” and “Equipment List.”

As an aside, it would be nice if we can consistently use “Equipment” rather than “Equipments” (with an “s” at the end).

**Comment by chunky56** [comment]
There are lots of labeling changes that need to be done in the product. I don't want to shoehorn it in here. At the very least, we can make it a separate story/branch.

**Pull request merged**
