### PR TITLE
Add feature toggle mechanism

### PR DESCRIPTION
**Pull request by chunky56**
https://openlmis.atlassian.net/wiki/display/OP/2.0+Feature+Toggle+Mechanism

### CODE REVIEW

**Comment by chunky56** [comment]
@joshzamor @eliasmu Elias, take a look in particular at commit a2c1e66, which is what you would want to cherry pick for eLMIS.

**Comment by joshzamor** [comment]
It looks like there is a merge conflict that needs to be resolved before merge.

A couple notes:
* it'd be great to document, close to the source, exactly how an implementation would toggle on/off
* also on the documentation front it'd be great to document how this would be utilized
* the column configuration_settings.isconfigurable is awfully convenient!  Be great if we noted the how and why of this close to source as well.

Aside from documentation and current merge conflict it's looking great! :+1:

**Comment by chunky56** [comment]
What do you mean by document 'how this would be utilized' and how is it different from the first point?

**Comment by joshzamor** [comment]
The first one I mean:  document how to use toggle on/off.
The second point I mean:  how would I as a developer turn my new stuff on/off following this pattern.  

Would be great for you to note approach, as though it's the same approach, data driven, you have a second in that column, which I put in the third point.

Third point is that it'd be great in general to note how this column works, even though you didn't add it here.  More a nice to have.

**Comment by chunky56** [comment]
Merging shortly as no comments for 7 days in pull request and no comments for 2 days after tech committee meeting.

**Pull request merged**
