### PR TITLE
OLMIS-66 remove a few more instances of MPL

### PR DESCRIPTION
**Pull request by richmag**

### CODE REVIEW

**Comment by benleibert** [comment]
Good catch on the removal of our license and copyright from "ng-grid-2.0.5.debug.js." I don't think our license/copyright belongs in the other two files, though. The "jasmine-gradle.js" library file seems to be part of this project: https://github.com/dzhaughnroth/jasmine-gradle-plugin. Although I didn't see "ui-sortable.js" online, my guess is that we didn't author it either. (Perhaps it was generated by a tool, the way jQuery related files sometime are.)

**Comment by eliasmu** [comment]
I would second that on jasmin-gradle - the ui-sortable.js was an early version of https://github.com/angular-ui/ui-sortable

**Comment by richmag** [comment]
Thanks for the feedback.  I will make a new commit soon.

**Comment by richmag** [comment]
I messed up with git.  Closing this and creating new pull request

**Pull request closed without merging**
